### PR TITLE
Feature Update

### PR DESCRIPTION
**Pull request by zellneralex**
New Features:
- Custom macros inside PAUSE/RESUME/CANCEL_PRINT
- RESUME Safeguard features
  - Possibility to add a filament runout sensor
  - Usage of [extruder].min_extrude_temp
  
Fixes: 
- Save/Restore extruder temperature on pause/resume
Please read the README.md as that needs a change in the [idle_timeout] gcode section.

Signed-off-by: Alex Zellner [alexander.zellner@googlemail.com](mailto:alexander.zellner@googlemail.com)

### CODE REVIEW

**Comment by TMTYD** [comment]
Hi

How is it possible to specify a specific extruder temperature when cancelling the print? For example, when I cancel the print, I want it to lower the temperature to 120 degrees and the bed to 40 degrees

**Comment by meteyou** [comment]
@TMTYD for help, pls use the discussions or our discord server.

**Comment by zellneralex** [comment]
@TMTYD it will always switch off heaters see  https://github.com/mainsail-crew/mainsail-config/blob/master/client.cfg#L84.

the only way would be write your own small macro that sets the temps and at it as user_cancel_macro

**Comment by TMTYD** [comment]
Hi Alex, 

Das habe ich versucht mit dem 

`    {% set EXTRUDER_TEMP = params.EXTRUDER_TEMP|default(190)|float %}

M109 S{EXTRUDER_TEMP}
`

Nachdem gcode:

Aber das hat mich geklappt

**Comment by zellneralex** [comment]
As said you need to do your own macro, e.g

```
[gcode_macro my_cancel_temp]
gcode:
  M109 S120
  M104 S40
```


And than add 
user_cancel_macro: my_cancel_temp

to your user block

**Comment by TMTYD** [comment]
Thx i test it

**Comment by TMTYD** [comment]
> As said you need to do your own macro, e.g
> 
> ```
> [gcode_macro my_cancel_temp]
> gcode:
>   M109 S120
>   M104 S40
> ```
> 
> And than add user_cancel_macro: my_cancel_temp
> 
> to your user block

thx it works

**Pull request merged**
