### PR TITLE
Refactor duplicated code into separate EXTRUDE/RETRACT macros

### PR DESCRIPTION
**Pull request by JamShady**
Refactored the existing code to remove repetition, and make ongoing maintenance easier by improving readability, and providing a single point where updates need to be made. It also allows for code reuse in custom macros by the end user.

The EXTRUDE gcode is an almost identical implementation of the original, whereas RETRACT mostly leverages the functionality in EXTRUDE.

An update I would like to make, but not sure how (if it's possible) is to eliminate the speed param management in RETRACT, and have this parameter (if supplied) automagically passed through to EXTRUDE. I wasn't sure of the cleanest/best way to do that.

### CODE REVIEW

**Comment by zellneralex** [comment]
I still need to get a closer look to it, but why using 2 macros?

If we get the code out it would be better to do a macro e.g (I have no good name yet) _filament METHOD=retract. Then you would use the METHODE [retract/extrude] to get the variables from the _CLIENT_VARIABLE macro
Currently you are close to it your _RETRACT macro only setup some parameters

**Comment by zellneralex** [comment]
Furthermore and yes I know that sounds crazy we need to pick macro names that no one else will use. 
The reason for that is that Klipper will throw an error if you have 2 macros in your config having the same name, so we need to insure that the mainsail.cfg most likely is not interfering with regular configs.

**Comment by zellneralex** [comment]
To give you an idea what I mean:
```
# USAGE: _MY_AWESOME_NEW_NAME METHOD=<[retract/extrude]> [LENGTH=<value>]
[gcode_macro _MY_AWESOME_NEW_NAME]
description: need description
gcode:
  {% set method = params.METHOD|default('extrude')|lower %}
  {% set macro_found = True if printer['gcode_macro _CLIENT_VARIABLE'] is defined else False %}
  {% set client = printer['gcode_macro _CLIENT_VARIABLE'] %}
  {% set use_fw_retract = False if not macro_found
                     else False if client.use_fw_retract is not defined
                     else True  if client.use_fw_retract|lower == 'true' and printer.firmware_retraction is defined
                     else False %}
  {% set length_in = (params.LENGTH|float|abs) if params.LENGTH is defined
                else 1.0 if not macro_found
                else client.unretract|default(1.0) if method == 'extrude' 
                else client.retract|default(1.0)   if method == 'retract'%}
  {% set lenght = length_in if method == 'extrude' else length_in * -1 %}
  {% set speed = 35 if not macro_found
            else client.speed_unretract|default(35) if method == 'extrude'
            else client.speed_retract|default(35)   if method == 'retract' %}
  {% set absolute_extrude = printer.gcode_move.absolute_extrude %}
  {% if printer.extruder.can_extrude %}
    {% if use_fw_retract %}
      {% if method == 'retract' %} G10 {% else %} G11 {% endif %}
    {% else %}
      M83
      G1 E{length} F{(speed|float|abs) * 60}
      {% if absolute_extrude %} M82 {% endif %}
    {% endif %}
  {% else %}
    {action_respond_info("Extruder not hot enough")}
  {% endif %}
  ```
DISCLAIMER: This was fast typend in without even testing if it is syntactical correct. It should only show you what I mean

**Comment by zellneralex** [comment]
If we would also like to get rid off the LENGHT parameter we could change the METHOD parameter to [pause,resume,cancel] and set the parameter accordingly.

If I think about it that would be the best solution in my opinion. So something like:
```
# USAGE: _MY_AWESOME_NEW_NAME METHOD=<[pause/resume/cancel]>
[gcode_macro _MY_AWESOME_NEW_NAME]
description: Helper: need description
gcode:
  {% set method = params.METHOD|default(‘pause’) %}
  {% set macro_found = True if printer['gcode_macro _CLIENT_VARIABLE'] is defined else False %}
  {% set client = printer['gcode_macro _CLIENT_VARIABLE'] %}
  {% set use_fw_retract = False if not macro_found
                     else False if client.use_fw_retract is not defined
                     else True  if client.use_fw_retract|lower == 'true' and printer.firmware_retraction is defined
                     else False %}
  {% set length_in = 1.0 if not macro_found and method is in [‘pause’, ‘resume’]
                else 5.0 if not macro_found and method == ‘cancel’
                else client.unretract|default(1.0)       if method == 'resume' 
                else client.retract|default(1.0)         if method == 'pause' 
                else client. cancel_retract|default(5.0) if method == 'cancel' %}
  {% set lenght = length_in|abs if method == 'resume' else length_in|abs * -1 %}
  {% set speed = 35 if not macro_found
            else client.speed_unretract|default(35) if method == 'resume'
            else client.speed_retract|default(35)   if method is in [‘pause’, ‘cancel’] %}
  {% set absolute_extrude = printer.gcode_move.absolute_extrude %}
  {% if printer.extruder.can_extrude %}
    {% if use_fw_retract %}
      {% if method == 'resume' %} G11 {% else %} G10 {% endif %}
    {% else %}
      M83
      G1 E{length} F{(speed|float|abs) * 60}
      {% if absolute_extrude %} M82 {% endif %}
    {% endif %}
  {% else %}
    {action_respond_info("Extruder not hot enough")}
  {% endif %}
```

DISCLAIMER: This was fast typend in without even testing if it is syntactical correct. It should only show you what I mean

**Comment by JamShady** [comment]
**Why use two macros**: To make the intent abundantly clear. I come from a s/w dev background, and can't tell you the number of errors I've seen where a hard-to-spot typo has been made, which in this case can be the presence/absence of a minus sign. Reading extrude/retract avoids that for the sake of a little extra code, and is (imho) more intuitive.

**We need to pick macro names that no one else will use**: Yeah, I get that. They're already prefixed with underscores, does double-underscores work?

**If we would also like to get rid off the LENGHT parameter**: I kept that there because (a) imho it's better to not bind parameter values to usage, and perhaps more importantly (b) it allows for flexibility and re-use by the end user. In my particular setup, I use extrude/retract in my own custom gcodes and want the flexibility of defining my own length value without it being hard-tied to other parameters that might not make sense in the particular context I'm using it in.

The goal was to promote a generic method that can be reused and has more value, rather than hard-tying it to specific scenarios and not allowing the end-user to re-use the macro in other contexts.

**Comment by zellneralex** [comment]
My background is FPGA/ASIC development so in case of asic a typo in the code costs a lot of development time as you need to make new mask and silicon. We do not talk about the money involved in that.

Never tried double _ but I guess they will work. I agree with you reuse might be a good thing but from supporting it, I find out most users tend to use there own stuff or better say copied it from several sources, therefore I tend to make it hardcoded.

**Comment by JamShady** [comment]
I decided that double-underscore was too easy to mistype somewhere (it's not necessarily immediately obvious there are two underscores), so I prefixed the macros with _MS to denote MainSail. I hope that's ok?

Also, as for users using their own stuff, I'd say that's because they're forced to, because existing implementations don't provide reusable examples. Without the update in this PR, I'd have to reuse/duplicate the exact same code to get similar functionality in my own macros... but then might also end up hard-coding parameters to suit my own situation if I have to go that far, so in the end it'll look different.

With this reusable example, there's no need to do that anymore.

**Comment by zellneralex** [comment]
Use _CLIENT because that would match the variable macro. How about using the first idea (method + length) then you can easily make your own 2 macros for your personal use

**Comment by JamShady** [comment]
**Use _CLIENT because that would match the variable macro**: OK, sure. That's a good shout. I'll push that shortly.

**How about using the first idea (method + length) then you can easily make your own 2 macros for your personal use**: It's considered very bad practice to mix business and functional logic in code, especially in situations that don't warrant it, like this one (because there's no cost to making that separation aside from a little additional code, where there's more than enough memory surplus to accommodate). If we did this, we'd be mixing the 'why' an extrude is being done, with the mechanics of how to do it. If anything, the parameters from pause/cancel/etc should come from the pause/cancel macros, and leave extrude to just how much it needs to extrude (or retract, as the case may be).

**Comment by zellneralex** [comment]
I did not forget the PR. As you can see there is a branch with a new feature. The plan is to merge both on the same day so that the users only need to do one update.

**Pull request merged**
