### PR TITLE
docs: fix typos in mainsail.cfg comments

### PR DESCRIPTION
**Pull request by JamShady**

### CODE REVIEW

**Review by meteyou — APPROVED** [review]

**Comment by GDRPrint** [comment]
[Mainsail klipper macros and settings.odt](https://github.com/mainsail-crew/mainsail-config/files/10327793/Mainsail.klipper.macros.and.settings.odt)

**Comment by GDRPrint** [comment]
Corrected text

**Comment by zellneralex** [comment]
I will combine all these correction and commit as a separate PR

**Comment by zellneralex** [comment]
I merged all the corrections in https://github.com/mainsail-crew/mainsail-config/commit/1a1f1882cdf9e8b787c46eeedff8a6e46bc901fd

**Pull request closed without merging**
